DEFAULT_HOJA_PEDIDOS = "Hoja1"
DEFAULT_HOJA_STOCK = "Data"

FUZZY_THRESHOLD_DEFAULT = 80
FUZZY_THRESHOLD_MANY_CANDIDATES = 88
MANY_CANDIDATES_N = 5

CORS_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]